import type { RecommendationsResponse } from "@/lib/types";


export const DEFAULT_RECOMMENDATIONS: RecommendationsResponse = {
  mode: "preset",
  updated_at: "2026-03-30T00:00:00.000Z",
  categories: ["科技", "制造", "医药", "金融", "消费", "能源", "原材料", "基建与公用事业"],
  style_filters: ["核心池", "成长", "防御", "A股", "美股"],
  methodology:
    "首屏先展示固定观察池，方便快速浏览行业代表标的。点击右侧“实时分析推荐”后，系统才会调用后端接口，基于最新价格历史、成交量、新闻热度和分析师一致预期动态重排推荐结果。",
  data_sources: ["前端固定观察池"],
  groups: [
    {
      id: "preset-tech-ai",
      category: "科技",
      subcategory: "AI算力与半导体",
      description: "先看全球 AI 产业链里流动性和关注度最高的核心龙头。",
      stocks: [
        {
          symbol: "NVDA",
          company_name: "英伟达",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的 AI 核心标的，适合从算力主线切入后续单票研究。",
          tags: ["AI", "GPU", "龙头"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "TSM",
          company_name: "台积电",
          market: "US ADR",
          region: "中国台湾",
          rationale: "固定观察池里的先进制程代表，适合配合 AI 需求和晶圆周期一起看。",
          tags: ["晶圆代工", "先进制程", "核心供应链"],
          styles: ["核心池", "成长"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-manufacturing-ev",
      category: "制造",
      subcategory: "电动车与电池",
      description: "覆盖全球整车龙头和 A 股动力电池龙头，便于对照观察。",
      stocks: [
        {
          symbol: "TSLA",
          company_name: "特斯拉",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的高弹性制造标的，适合看整车、储能和机器人主线。",
          tags: ["电动车", "储能", "高波动"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "300750",
          company_name: "宁德时代",
          market: "CN A-share",
          region: "中国",
          rationale: "固定观察池里的 A 股电池龙头，适合从制造升级和储能链条展开研究。",
          tags: ["动力电池", "储能", "A股"],
          styles: ["核心池", "成长", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-healthcare",
      category: "医药",
      subcategory: "创新药与器械",
      description: "把创新药和高端器械放在同一页，方便快速切换研究主线。",
      stocks: [
        {
          symbol: "LLY",
          company_name: "礼来",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的创新药代表，适合跟踪减重药和创新药双主线。",
          tags: ["减重药", "创新药", "全球龙头"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ISRG",
          company_name: "直觉外科",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的高端器械代表，适合观察机器人手术平台化机会。",
          tags: ["手术机器人", "高端器械", "平台"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-finance",
      category: "金融",
      subcategory: "支付与金融信息",
      description: "优先放入现金流和护城河相对清晰的金融基础设施类公司。",
      stocks: [
        {
          symbol: "V",
          company_name: "Visa",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的全球支付网络核心标的，适合做防御型金融观察。",
          tags: ["支付", "网络效应", "高利润"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "SPGI",
          company_name: "标普全球",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的金融信息服务代表，适合跟踪数据和评级业务。",
          tags: ["评级", "指数", "数据"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-consumer",
      category: "消费",
      subcategory: "渠道与平台消费",
      description: "同时保留防御型消费和平台消费，方便快速切换风格。",
      stocks: [
        {
          symbol: "COST",
          company_name: "好市多",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的渠道消费龙头，适合放在稳健消费框架下研究。",
          tags: ["渠道", "会员", "防御"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "AMZN",
          company_name: "亚马逊",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的平台消费代表，适合连接电商与云业务的复合研究。",
          tags: ["电商", "云平台", "规模"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-energy",
      category: "能源",
      subcategory: "油气与新能源设备",
      description: "把传统能源和电网设备放在同一观察面板，兼顾周期与转型。",
      stocks: [
        {
          symbol: "XOM",
          company_name: "埃克森美孚",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的传统能源龙头，适合做现金流和分红框架观察。",
          tags: ["石油", "天然气", "现金流"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "GEV",
          company_name: "GE Vernova",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的电网设备代表，适合连接全球电气化和基建升级主题。",
          tags: ["电网", "设备", "能源转型"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-materials",
      category: "原材料",
      subcategory: "关键矿产",
      description: "围绕电气化和储能链条，保留高相关资源股作为观察入口。",
      stocks: [
        {
          symbol: "FCX",
          company_name: "自由港麦克莫兰",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的铜资源代表，适合从电气化主线回看资源弹性。",
          tags: ["铜", "矿业", "弹性"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ALB",
          company_name: "雅宝",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的锂资源代表，适合跟踪新能源链的上游周期。",
          tags: ["锂", "新能源", "高波动"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-infra",
      category: "基建与公用事业",
      subcategory: "数据中心与公用设施",
      description: "保留数字基础设施和公用设施龙头，适合做长期主题观察。",
      stocks: [
        {
          symbol: "EQIX",
          company_name: "Equinix",
          market: "US",
          region: "美国",
          rationale: "固定观察池里的中立数据中心平台，适合观察 AI 机柜扩容与长期租约逻辑。",
          tags: ["数据中心", "REIT", "基础设施"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "601012",
          company_name: "隆基绿能",
          market: "CN A-share",
          region: "中国",
          rationale: "固定观察池里的新能源设备代表，适合作为 A 股能源与基建主题入口。",
          tags: ["光伏", "A股", "周期"],
          styles: ["成长", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
  ],
};
