import type { RecommendationsResponse } from "@/lib/types";


export const DEFAULT_RECOMMENDATIONS: RecommendationsResponse = {
  mode: "preset",
  updated_at: "2026-04-04T00:00:00.000Z",
  categories: ["科技", "制造", "医药", "金融", "消费", "能源", "原材料", "基建与公用事业", "通信与娱乐", "国防与航空"],
  style_filters: ["核心池", "成长", "防御", "价值", "A股", "美股"],
  methodology:
    "首屏展示固定观察池，覆盖全球主要行业与赛道的核心标的。点击「实时分析推荐」后，系统调用后端接口基于最新数据动态排序。",
  data_sources: ["前端固定观察池"],
  groups: [
    // ── 科技 ─────────────────────────────────────────
    {
      id: "preset-tech-ai",
      category: "科技",
      subcategory: "AI算力与半导体",
      description: "全球 AI 产业链核心算力与芯片龙头。",
      stocks: [
        {
          symbol: "NVDA",
          company_name: "英伟达",
          market: "US",
          region: "美国",
          rationale: "AI GPU 绝对龙头，数据中心与训练推理双轮驱动。",
          tags: ["AI", "GPU"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "TSM",
          company_name: "台积电",
          market: "US ADR",
          region: "中国台湾",
          rationale: "全球先进制程晶圆代工垄断者，AI 芯片核心供应链。",
          tags: ["晶圆代工", "先进制程"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "AMD",
          company_name: "超威半导体",
          market: "US",
          region: "美国",
          rationale: "AI加速卡与数据中心CPU双线竞争者，MI系列GPU持续追赶。",
          tags: ["AI", "CPU"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "AVGO",
          company_name: "博通",
          market: "US",
          region: "美国",
          rationale: "定制AI芯片（ASIC）与网络芯片龙头，VMware整合带来软件收入。",
          tags: ["ASIC", "网络"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ASML",
          company_name: "阿斯麦",
          market: "US ADR",
          region: "荷兰",
          rationale: "EUV光刻机全球独家供应商，半导体设备的终极上游。",
          tags: ["光刻机", "设备"],
          styles: ["核心池", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-tech-software",
      category: "科技",
      subcategory: "软件与云计算",
      description: "全球企业软件与云基础设施核心玩家。",
      stocks: [
        {
          symbol: "MSFT",
          company_name: "微软",
          market: "US",
          region: "美国",
          rationale: "Azure云+Copilot AI双引擎，企业软件生态最完整的科技巨头。",
          tags: ["云计算", "AI"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ORCL",
          company_name: "甲骨文",
          market: "US",
          region: "美国",
          rationale: "Oracle Cloud基础设施高速增长，AI训练集群拿到大单。",
          tags: ["云计算", "数据库"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "CRM",
          company_name: "赛富时",
          market: "US",
          region: "美国",
          rationale: "全球CRM龙头，Agentforce AI代理平台推进企业AI落地。",
          tags: ["SaaS", "CRM"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ADBE",
          company_name: "Adobe",
          market: "US",
          region: "美国",
          rationale: "创意软件垄断者，Firefly AI生成式内容工具领先。",
          tags: ["创意软件", "AI"],
          styles: ["美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-tech-internet",
      category: "科技",
      subcategory: "互联网平台",
      description: "中美互联网超级平台，广告与电商双驱动。",
      stocks: [
        {
          symbol: "GOOGL",
          company_name: "谷歌",
          market: "US",
          region: "美国",
          rationale: "搜索广告+YouTube+GCP云+Gemini AI，全栈AI能力最强平台。",
          tags: ["搜索", "AI"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "META",
          company_name: "Meta",
          market: "US",
          region: "美国",
          rationale: "全球社交广告双寡头之一，Llama开源AI模型生态持续扩张。",
          tags: ["社交", "广告"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "BABA",
          company_name: "阿里巴巴",
          market: "US ADR",
          region: "中国",
          rationale: "中国电商+云计算龙头，通义千问大模型驱动AI转型。",
          tags: ["电商", "云计算"],
          styles: ["价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "PDD",
          company_name: "拼多多",
          market: "US ADR",
          region: "中国",
          rationale: "Temu全球化高速扩张，国内主站用户粘性与货币化持续提升。",
          tags: ["电商", "出海"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 制造 ─────────────────────────────────────────
    {
      id: "preset-manufacturing-ev",
      category: "制造",
      subcategory: "电动车与电池",
      description: "全球整车与动力电池产业链核心标的。",
      stocks: [
        {
          symbol: "TSLA",
          company_name: "特斯拉",
          market: "US",
          region: "美国",
          rationale: "全球电动车龙头，FSD自动驾驶+储能+Optimus机器人多线布局。",
          tags: ["电动车", "自动驾驶"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "300750",
          company_name: "宁德时代",
          market: "CN A-share",
          region: "中国",
          rationale: "全球动力电池出货量第一，麒麟电池与钠离子技术领先。",
          tags: ["动力电池", "储能"],
          styles: ["核心池", "成长", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "002594",
          company_name: "比亚迪",
          market: "CN A-share",
          region: "中国",
          rationale: "中国新能源车销量冠军，垂直整合芯片+电池+整车全产业链。",
          tags: ["电动车", "整车"],
          styles: ["核心池", "成长", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "LI",
          company_name: "理想汽车",
          market: "US ADR",
          region: "中国",
          rationale: "增程式SUV爆款制造者，盈利能力在新势力中最突出。",
          tags: ["电动车", "新势力"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-manufacturing-industrial",
      category: "制造",
      subcategory: "工业与自动化",
      description: "全球工业自动化与工程机械头部企业。",
      stocks: [
        {
          symbol: "HON",
          company_name: "霍尼韦尔",
          market: "US",
          region: "美国",
          rationale: "多元工业巨头，航空零部件+楼宇自控+工业自动化。",
          tags: ["工业", "自动化"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "CAT",
          company_name: "卡特彼勒",
          market: "US",
          region: "美国",
          rationale: "全球工程机械与矿业设备龙头，基建周期核心受益标的。",
          tags: ["工程机械", "基建"],
          styles: ["价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "300124",
          company_name: "汇川技术",
          market: "CN A-share",
          region: "中国",
          rationale: "中国工业自动化龙头，伺服与变频器国产替代加速。",
          tags: ["自动化", "伺服"],
          styles: ["成长", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 医药 ─────────────────────────────────────────
    {
      id: "preset-healthcare-drug",
      category: "医药",
      subcategory: "创新药",
      description: "全球创新药管线与商业化领先的大型药企。",
      stocks: [
        {
          symbol: "LLY",
          company_name: "礼来",
          market: "US",
          region: "美国",
          rationale: "GLP-1减重药赛道领跑者，替尔泊肽全球销售爆发式增长。",
          tags: ["减重药", "创新药"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "NVO",
          company_name: "诺和诺德",
          market: "US ADR",
          region: "丹麦",
          rationale: "GLP-1赛道先行者，司美格鲁肽全球份额领先。",
          tags: ["减重药", "糖尿病"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "MRK",
          company_name: "默沙东",
          market: "US",
          region: "美国",
          rationale: "Keytruda全球肿瘤免疫治疗标杆，管线深度行业领先。",
          tags: ["肿瘤", "免疫"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ABBV",
          company_name: "艾伯维",
          market: "US",
          region: "美国",
          rationale: "Humira继任药Skyrizi/Rinvoq增长强劲，高分红生物药企。",
          tags: ["免疫", "分红"],
          styles: ["防御", "价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-healthcare-device",
      category: "医药",
      subcategory: "器械与医疗服务",
      description: "高端医疗器械与综合医疗服务平台。",
      stocks: [
        {
          symbol: "ISRG",
          company_name: "直觉外科",
          market: "US",
          region: "美国",
          rationale: "达芬奇手术机器人全球垄断，装机量与手术量持续创新高。",
          tags: ["手术机器人", "器械"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "TMO",
          company_name: "赛默飞",
          market: "US",
          region: "美国",
          rationale: "全球生命科学仪器与耗材龙头，实验室设备一站式供应商。",
          tags: ["仪器", "生命科学"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "UNH",
          company_name: "联合健康",
          market: "US",
          region: "美国",
          rationale: "美国最大健康保险与医疗服务集团，Optum数据驱动业务高增。",
          tags: ["医保", "服务"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 金融 ─────────────────────────────────────────
    {
      id: "preset-finance-payment",
      category: "金融",
      subcategory: "支付与金融科技",
      description: "全球支付网络与金融科技核心平台。",
      stocks: [
        {
          symbol: "V",
          company_name: "Visa",
          market: "US",
          region: "美国",
          rationale: "全球最大支付网络，跨境支付与数字化渗透持续增长。",
          tags: ["支付", "网络"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "MA",
          company_name: "万事达卡",
          market: "US",
          region: "美国",
          rationale: "全球第二大支付网络，增值服务与数据分析收入占比提升。",
          tags: ["支付", "数据"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "PYPL",
          company_name: "PayPal",
          market: "US",
          region: "美国",
          rationale: "全球在线支付先驱，Venmo+Braintree覆盖C端与B端。",
          tags: ["在线支付", "金融科技"],
          styles: ["价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-finance-bank",
      category: "金融",
      subcategory: "银行与保险",
      description: "全球系统重要性银行与保险龙头。",
      stocks: [
        {
          symbol: "JPM",
          company_name: "摩根大通",
          market: "US",
          region: "美国",
          rationale: "全球资产规模最大银行，投行+零售+资管全业务线领先。",
          tags: ["银行", "投行"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "GS",
          company_name: "高盛",
          market: "US",
          region: "美国",
          rationale: "全球顶级投行，交易与资产管理业务在利率环境中受益。",
          tags: ["投行", "交易"],
          styles: ["美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "601318",
          company_name: "中国平安",
          market: "CN A-share",
          region: "中国",
          rationale: "中国综合金融龙头，寿险改革转型+医疗健康生态布局。",
          tags: ["保险", "综合金融"],
          styles: ["价值", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-finance-info",
      category: "金融",
      subcategory: "金融信息与交易所",
      description: "金融数据、评级与交易基础设施服务商。",
      stocks: [
        {
          symbol: "SPGI",
          company_name: "标普全球",
          market: "US",
          region: "美国",
          rationale: "全球信用评级与金融数据龙头，指数业务护城河极深。",
          tags: ["评级", "数据"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ICE",
          company_name: "洲际交易所",
          market: "US",
          region: "美国",
          rationale: "NYSE母公司，拥有全球最大能源期货交易所与固收数据平台。",
          tags: ["交易所", "数据"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 消费 ─────────────────────────────────────────
    {
      id: "preset-consumer-ecommerce",
      category: "消费",
      subcategory: "电商与零售",
      description: "全球电商平台与渠道零售龙头。",
      stocks: [
        {
          symbol: "AMZN",
          company_name: "亚马逊",
          market: "US",
          region: "美国",
          rationale: "全球电商+AWS云双引擎，AI与物流基础设施持续投入。",
          tags: ["电商", "云平台"],
          styles: ["核心池", "成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "COST",
          company_name: "好市多",
          market: "US",
          region: "美国",
          rationale: "会员制仓储超市标杆，全球续费率超90%，防御属性极强。",
          tags: ["零售", "会员"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "WMT",
          company_name: "沃尔玛",
          market: "US",
          region: "美国",
          rationale: "全球最大零售商，电商与广告业务转型成效显现。",
          tags: ["零售", "全渠道"],
          styles: ["防御", "价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-consumer-brand",
      category: "消费",
      subcategory: "品牌与白酒",
      description: "全球消费品牌与中国白酒龙头。",
      stocks: [
        {
          symbol: "NKE",
          company_name: "耐克",
          market: "US",
          region: "美国",
          rationale: "全球运动品牌龙头，DTC直营转型与新产品周期驱动。",
          tags: ["运动", "品牌"],
          styles: ["价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "600519",
          company_name: "贵州茅台",
          market: "CN A-share",
          region: "中国",
          rationale: "中国白酒之王，品牌溢价与定价权构成极深护城河。",
          tags: ["白酒", "品牌"],
          styles: ["核心池", "防御", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "000858",
          company_name: "五粮液",
          market: "CN A-share",
          region: "中国",
          rationale: "中国浓香型白酒龙头，高端化与渠道改革持续推进。",
          tags: ["白酒", "高端"],
          styles: ["价值", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-consumer-food",
      category: "消费",
      subcategory: "餐饮与食品",
      description: "全球食品饮料与餐饮连锁核心标的。",
      stocks: [
        {
          symbol: "KO",
          company_name: "可口可乐",
          market: "US",
          region: "美国",
          rationale: "全球饮料帝国，品牌组合与分销网络无可匹敌。",
          tags: ["饮料", "分红"],
          styles: ["防御", "价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "MCD",
          company_name: "麦当劳",
          market: "US",
          region: "美国",
          rationale: "全球快餐龙头，特许经营模式带来稳定现金流与高利润率。",
          tags: ["餐饮", "特许"],
          styles: ["防御", "价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "SBUX",
          company_name: "星巴克",
          market: "US",
          region: "美国",
          rationale: "全球咖啡连锁龙头，中国市场恢复与运营效率改善。",
          tags: ["咖啡", "连锁"],
          styles: ["价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 能源 ─────────────────────────────────────────
    {
      id: "preset-energy-oil",
      category: "能源",
      subcategory: "油气",
      description: "全球传统能源超级巨头。",
      stocks: [
        {
          symbol: "XOM",
          company_name: "埃克森美孚",
          market: "US",
          region: "美国",
          rationale: "全球市值最大油气公司，盈亚那深水油田带来长期增长。",
          tags: ["石油", "分红"],
          styles: ["防御", "价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "CVX",
          company_name: "雪佛龙",
          market: "US",
          region: "美国",
          rationale: "全球综合油气龙头，二叠纪盆地产量增长与高股息回报。",
          tags: ["石油", "天然气"],
          styles: ["防御", "价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-energy-renewables",
      category: "能源",
      subcategory: "新能源与电网",
      description: "全球能源转型与电网升级核心设备商。",
      stocks: [
        {
          symbol: "GEV",
          company_name: "GE Vernova",
          market: "US",
          region: "美国",
          rationale: "全球电力设备龙头，燃气轮机+风电+电网三大板块受益电气化。",
          tags: ["电网", "设备"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ENPH",
          company_name: "Enphase",
          market: "US",
          region: "美国",
          rationale: "户用光伏微型逆变器龙头，IQ系列能源管理平台化。",
          tags: ["光伏", "逆变器"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "601012",
          company_name: "隆基绿能",
          market: "CN A-share",
          region: "中国",
          rationale: "全球光伏硅片与组件龙头，BC电池技术路线引领行业。",
          tags: ["光伏", "硅片"],
          styles: ["成长", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 原材料 ───────────────────────────────────────
    {
      id: "preset-materials-mining",
      category: "原材料",
      subcategory: "矿产资源",
      description: "全球电气化与储能链条的上游关键矿产。",
      stocks: [
        {
          symbol: "FCX",
          company_name: "自由港麦克莫兰",
          market: "US",
          region: "美国",
          rationale: "全球最大上市铜矿商，电气化主线的纯铜标的。",
          tags: ["铜", "矿业"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "ALB",
          company_name: "雅宝",
          market: "US",
          region: "美国",
          rationale: "全球锂资源巨头，锂价周期底部的弹性标的。",
          tags: ["锂", "周期"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "NEM",
          company_name: "纽蒙特",
          market: "US",
          region: "美国",
          rationale: "全球最大黄金矿商，金价创新高时的核心受益标的。",
          tags: ["黄金", "避险"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-materials-chemical",
      category: "原材料",
      subcategory: "化工",
      description: "全球特种气体与化工材料头部企业。",
      stocks: [
        {
          symbol: "LIN",
          company_name: "林德",
          market: "US",
          region: "爱尔兰",
          rationale: "全球最大工业气体公司，半导体与氢能产业链核心供应商。",
          tags: ["工业气体", "半导体"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "600309",
          company_name: "万华化学",
          market: "CN A-share",
          region: "中国",
          rationale: "全球MDI产能第一，向新材料与精细化工扩展。",
          tags: ["MDI", "化工"],
          styles: ["价值", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 基建与公用事业 ──────────────────────────────
    {
      id: "preset-infra-datacenter",
      category: "基建与公用事业",
      subcategory: "数据中心与通信塔",
      description: "数字基础设施REITs，AI算力需求核心受益。",
      stocks: [
        {
          symbol: "EQIX",
          company_name: "Equinix",
          market: "US",
          region: "美国",
          rationale: "全球最大中立数据中心运营商，AI扩容带动长期租约增长。",
          tags: ["数据中心", "REIT"],
          styles: ["核心池", "防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "DLR",
          company_name: "Digital Realty",
          market: "US",
          region: "美国",
          rationale: "全球第二大数据中心REIT，大规模AI训练集群部署受益。",
          tags: ["数据中心", "REIT"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "AMT",
          company_name: "美国电塔",
          market: "US",
          region: "美国",
          rationale: "全球最大无线通信塔运营商，5G部署与新兴市场渗透。",
          tags: ["通信塔", "REIT"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
    {
      id: "preset-infra-utility",
      category: "基建与公用事业",
      subcategory: "电力与公用设施",
      description: "清洁能源电力与传统公用事业龙头。",
      stocks: [
        {
          symbol: "NEE",
          company_name: "NextEra Energy",
          market: "US",
          region: "美国",
          rationale: "全球最大风电与光伏发电商，清洁能源公用事业标杆。",
          tags: ["清洁能源", "公用"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "600900",
          company_name: "长江电力",
          market: "CN A-share",
          region: "中国",
          rationale: "中国水电龙头，三峡+葛洲坝+乌白水电站稳定现金流。",
          tags: ["水电", "分红"],
          styles: ["核心池", "防御", "A股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 通信与娱乐 ──────────────────────────────────
    {
      id: "preset-media-streaming",
      category: "通信与娱乐",
      subcategory: "流媒体与内容",
      description: "全球流媒体与内容娱乐核心平台。",
      stocks: [
        {
          symbol: "NFLX",
          company_name: "奈飞",
          market: "US",
          region: "美国",
          rationale: "全球流媒体订阅龙头，广告层级与体育直播开辟新增长曲线。",
          tags: ["流媒体", "内容"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "DIS",
          company_name: "迪士尼",
          market: "US",
          region: "美国",
          rationale: "全球IP帝国，主题公园+Disney+流媒体+ESPN体育多线并进。",
          tags: ["娱乐", "IP"],
          styles: ["价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "SPOT",
          company_name: "Spotify",
          market: "US",
          region: "瑞典",
          rationale: "全球音频流媒体龙头，付费用户与利润率同步改善。",
          tags: ["音乐", "订阅"],
          styles: ["成长", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },

    // ── 国防与航空 ──────────────────────────────────
    {
      id: "preset-defense",
      category: "国防与航空",
      subcategory: "军工与航空航天",
      description: "全球国防承包商与航空航天核心企业。",
      stocks: [
        {
          symbol: "LMT",
          company_name: "洛克希德马丁",
          market: "US",
          region: "美国",
          rationale: "美国最大国防承包商，F-35隐身战斗机独家制造商。",
          tags: ["军工", "航空"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "RTX",
          company_name: "RTX公司",
          market: "US",
          region: "美国",
          rationale: "普惠发动机+雷神导弹与防御系统，军民航空双轮驱动。",
          tags: ["发动机", "导弹"],
          styles: ["防御", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
        {
          symbol: "BA",
          company_name: "波音",
          market: "US",
          region: "美国",
          rationale: "全球民航双寡头之一，积压订单达数千架，产能恢复是关键变量。",
          tags: ["航空", "制造"],
          styles: ["价值", "美股"],
          scorecard: null,
          evidence: null,
          data_sources: ["固定观察池"],
        },
      ],
    },
  ],
};
